name: Sync to Gitee

on: [ push, delete, create ]

jobs:
  deploy-site-sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings -> Secrets 配置 GITEE_RSA_PRIVATE_KEY
          # 也可以在组织 Settings -> Secrets 配置全局性的 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:hellof2e/gluang.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:hellof2e/gluang.git